# Welcome to Jekyll!
#

# Site settings
title: Lancaster Steel
description: Classic Design. Modern Craftsmanship.
owner: M&A Group # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: ballport@lancastersteel.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lancastersteel.com" # the base hostname & protocol for your site
social:
  #twitter: https://twitter.com/Lancaster_steel

  #linkedin-square: https://linkedin.com/in/<username>
  #facebook-official: https://facebook.com/<username>
  #google-plus-square: https://plus.google.com/u/0/+<username>
  #email: ballport@lancastersteel.com
  #flickr:
  instagram: http://instagram.com/lancastersteel
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  amazon: http://amazon.com/Whiskey-Glass-Fashioned-10oz-Lowball/dp/B01DYPXNWE/ref=sr_1-34?ie=UTF8&qid=1463762399&sr=8-34&keywords=stainless+steel+whiskey+tumbler
  pinterest: https://www.pinterest.com/lancastersteel/
  twitter: https://www.twitter.com/lancaster_steel/
# Build settings
markdown: kramdown
#sass:
#  style: compressed
